name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '*/5 * * * *'

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
    # Step 1: Prepare the environment
    - name: Check out this repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    # Step 2: Get the latest data and store it as a CSV
    - name: Fetch latest data
      run: |-        
        curl "https://gbfs.bird.co/dc" -o bird_current.json
        curl "https://s3.amazonaws.com/lyft-lastmile-production-iad/lbs/dca/free_bike_status.json" -o lyft_current.json
        curl "https://data.lime.bike/api/partners/v1/gbfs/washington_dc/free_bike_status.json" -o lime_current.json
        curl "https://admin-api-prod.helbizscooters.com//reporting/washington/gbfs/free_bike_status.json" -o helbiz_current.json
        curl "https://gbfs.spin.pm/api/gbfs/v1/washington_dc/free_bike_status" -o spin.json
    # Step 3: Commit and push
    - name: Commit and push
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
